databases:
  - name: django-bona-blog
    databaseName: django-bona-blog
    user: django-bona-blog

services:
  - type: web
    name: mysite
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-bona-blog
          property: connectionString
      - key: SECRET_KEY
        generateValue: true 
      - key: WEB_CONCURRENCY
        value: 4