databases:
  - name: django-bona-blog
    databaseName: bonablog
    user: bona

services:
  - type: web
    name: djangobonablog
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn djangobonablog.wsgi:application"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-bona-blog
          property: connectionString
      - key: SECRET_KEY
        generateValue: true 
      - key: WEB_CONCURRENCY
        value: 4
